### ISSUE TITLE
roles defined in playbook as list of dicts fails

### ISSUE THREAD

**Issue by urwotu8** [RebelCodeBase/testaid#10]
ie (from playbook - valid as per `https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html`) :- 
```
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
```
results in 
```
self = <testaid.moleculeenv.MoleculeEnv object at 0x111975710>
roles = [{'role': 'linux_common'}, {'role': 'product_common'}, {'role': 'product_install'}]
    def _create_roles_symlinks_(self, roles):
        (self.get_molecule_ephemeral_directory() / 'roles').mkdir(
            exist_ok=True)
        for role in roles:
>           self._create_symlink_('roles/' + role)
E           TypeError: can only concatenate str (not "dict") to str
../../.venv/lib/python3.7/site-packages/testaid/moleculeenv.py:92: TypeError
```
